### ISSUE TITLE
Add datarequests count

### ISSUE THREAD

**Issue by jqnatividad** [conwetlab/ckanext-datarequests#3]
So it can be shown in box_stats?  See https://github.com/ckan/ckanext-showcase/blob/master/ckanext/showcase/templates/home/snippets/stats.html

**Comment by aitormagan** [comment]
It's a great suggestion. I'll try to implement it ASAP! :)

**Comment by jqnatividad** [comment]
Hi @aitormagan, thought you may want to check this PR before implementing https://github.com/ckan/ckan/pull/2400

**Comment by aitormagan** [comment]
Thank you for the support! :)

**Comment by aitormagan** [comment]
I've tried to do this but it seems complicated since there can be two different extensions that can extend the template and the behaviour in this case is strange (the template parsed it's different every time). In your case I guess you have one extension that extends the `stats.html` file so I think it's up to you to add the data requests count in your stats snippet. 

I'm really sorry :(

**Comment by jqnatividad** [comment]
No apologies required @aitormagan!  I guess that will have to be customized on an instance per instance basis.  Thanks!
